
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_review_development
      TZ: Asia/Tokyo
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: bike_review_development
      TZ: Asia/Tokyo

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    environment:
      TZ: Asia/Tokyo

volumes:
  postgres-data:
  bundle_data:
  node_modules:


