name: Rails CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bike_review_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d bike_review_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: bike_review_test
      USE_REMOTE_CHROME: "false"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -U postgres; do echo "Waiting for postgres..."; sleep 1; done

      - name: Prepare DB
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run RSpec (rack_test)
        run: |
