name: RuboCop Lint (Docker)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      GOOGLE_MAPS_API_KEY: dummy_key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose
        run: docker compose build

      - name: Run RuboCop
        run: docker compose run --rm -e RAILS_ENV -e GOOGLE_MAPS_API_KEY web bundle exec rubocop
