name: RuboCop Lint (Docker)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run RuboCop
        run: docker-compose run --rm web bundle exec rubocop
